name = "weekly-routine-api"
main = "src/index.js"
compatibility_date = "2025-01-01"

# Filled in after `wrangler kv namespace create ROUTINE_KV`
kv_namespaces = [
  { binding = "ROUTINE_KV", id = "fb43b0b0ed0b45fcbd0da1c2277d56e6" }
]
